package:
  name: foyer
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ../../

build:
  noarch: python
  ignore_run_exports:
    - python
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0)}}
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
          - load_OPLSAA = foyer.forcefields.forcefields:load_OPLSAA
          - load_TRAPPE_UA = foyer.forcefields.forcefields:load_TRAPPE_UA

requirements:
  build:
    - python

  run:
    - parmed
    - networkx >=2.0
    - openmm
    - lark-parser
    - requests
    - lxml

test:
  requires:
    - mbuild
    - pytest >=3.0
    - pytest-timeout
    - requests-mock

  source_files:
    - foyer/forcefields/*
    - foyer/opls_validation/*
    - foyer/tests/files/*
    - foyer/tests/*.txt

  commands:
    - set LNAME=appveyor
    - py.test -v --pyargs foyer

about:
  home: http://mosdef-hub.github.io/foyer
  license: MIT
  summary: Atomtyping and forcefield applying.
